# backend/Dockerfile.lockgenerator
FROM python:3.11

WORKDIR /app

# Install Poetry using pip
RUN python3 -m pip install poetry==1.8.2

# Copy only pyproject.toml
COPY pyproject.toml /app/

# Generate the lock file
RUN poetry lock

# Output the generated lock file to stdout
CMD cat poetry.lock 