services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit for faster builds
      args:
        BUILDKIT_INLINE_CACHE: 1
    command: ./docker-entrypoint.sh
    environment:
      - DEBUG=1
      - LOG_LEVEL=DEBUG
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Use host.docker.internal to access the SSH tunnel on the host machine
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      # For Vertex AI Anthropic integration
      - GOOGLE_APPLICATION_CREDENTIALS=/app/vertexai.json
      - VERTEX_AI_PROJECT=${VERTEX_AI_PROJECT}
      - VERTEX_AI_LOCATION=europe-west3
      # For database and storage access
      - GCS_SERVICE_ACCOUNT_KEY=/app/key.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GCS_ENABLED=${GCS_ENABLED}
      # LLM Settings
      - DEFAULT_LLM_PROVIDER=vertex_ai
      - DEFAULT_LLM_MODEL=gemini-2.0-flash
      - VERTEX_AI_ENABLED=true
      - VERTEX_AI_PROJECT_ID=${VERTEX_AI_PROJECT_ID}
      - VERTEX_AI_LOCATION=europe-west4
      # Auth0
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
    volumes:
      - ./tests:/app/tests
      - ./key.json:/app/key.json
      - ./vertexai.json:/app/vertexai.json
    ports:
      - "8001:8001"  # FastAPI main application port
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - qdrant

  # Add local Qdrant container
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always 