services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit for faster builds
      args:
        BUILDKIT_INLINE_CACHE: 1
    command: ./docker-entrypoint.sh
    environment:
      - DEBUG=1
      - LOG_LEVEL=DEBUG
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Use host.docker.internal to access the SSH tunnel on the host machine
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      # For Vertex AI Anthropic integration
      - GOOGLE_APPLICATION_CREDENTIALS=/app/vertexai.json
      - VERTEX_AI_PROJECT=${VERTEX_AI_PROJECT}
      - VERTEX_AI_LOCATION=europe-west3
      # For database and storage access
      - GCS_SERVICE_ACCOUNT_KEY=/app/key.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GCS_ENABLED=${GCS_ENABLED}
      # MCP Agent Settings
      - MCP_AGENT_ENABLED=true
      - MCP_CONFIG_PATH=/app/mcp_local/mcp_agent.config.yaml
      # Anthropic API Settings
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=claude-3-7-sonnet-20250219
      # Qdrant Settings - IMPORTANT: Force using the local qdrant container
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=denker_embeddings
      - QDRANT_ENABLED=true
      - QDRANT_VECTOR_SIZE=768
      - USE_LOCAL_QDRANT=true
      # QDRANT_SEARCH_LIMIT=3
      # Google Search API - Required for websearch server
      - GOOGLE_API_KEY=AIzaSyCa_aJ2I3j3L47mTI4YLSZYfI0moRnyw7A
      - GOOGLE_CSE_ID=40d4f27f2b3a24796
      # LLM Settings
      - DEFAULT_LLM_PROVIDER=vertex_ai
      - DEFAULT_LLM_MODEL=gemini-2.0-flash
      - VERTEX_AI_ENABLED=true
      - VERTEX_AI_PROJECT_ID=${VERTEX_AI_PROJECT_ID}
      - VERTEX_AI_LOCATION=europe-west4
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
    volumes:
      # - .:/app # <-- COMMENTED OUT TO PREVENT OVERRIDING INSTALLED PACKAGES
      - ./tests:/app/tests
      - ./key.json:/app/key.json
      - ./vertexai.json:/app/vertexai.json
      - ${HOME}/Desktop:/user_desktop
      - ${HOME}/Downloads:/user_downloads
    ports:
      - "8001:8001"  # FastAPI main application port
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - qdrant

  # Add local Qdrant container
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always 