"""Initial migration

Revision ID: 00fe537abe67
Revises: 
Create Date: 2025-03-23 19:13:51.305059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fe537abe67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trieve_dataset_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trieve_dataset_id')
    # ### end Alembic commands ### 