"""add is_processed to files

Revision ID: 11cf511cdd47
Revises: 1e7db0360b2f
Create Date: 2025-04-01 12:32:30.341730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cf511cdd47'
down_revision = '1e7db0360b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_processed')
    # ### end Alembic commands ### 