"""rename_file_path_to_storage_path

Revision ID: 1e7db0360b2f
Revises: 00fe537abe67
Create Date: 2025-03-31 07:17:07.718378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7db0360b2f'
down_revision = '00fe537abe67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, delete any agent_logs entries with NULL query_id
    op.execute("DELETE FROM agent_logs WHERE query_id IS NULL")
    
    op.create_table('search_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_query_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('agent_logs', 'agent_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agent_logs', 'query_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agent_logs', 'processing_time',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file_attachments', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file_attachments', 'file_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('files', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('files', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('files', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('files', 'is_processed')
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('files', sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('files', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('files', 'deleted_at')
    op.drop_column('files', 'updated_at')
    op.alter_column('file_attachments', 'file_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('file_attachments', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agent_logs', 'processing_time',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('agent_logs', 'query_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agent_logs', 'agent_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('document_chunks')
    op.drop_table('search_results')
    op.drop_table('documents')
    op.drop_table('search_queries')
    # ### end Alembic commands ### 